### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by CrimsonTome** [hullcss/conduct#1]
16) Members must not harass another member, Exec, Mod either in person, on Discord, during 
events or at any other point.
a. https://respectyourself.info/sex/consent/enthusiastic-consent/ is harassment, or even 
abuse.
b. Clothing or flirting are not necessarily consent. If you are asked to stop, stop. If in 
doubt, ask the other person.

 https://respectyourself.info/sex/consent/enthusiastic-consent/  - respectyourself is under review. The link does not work.

**Comment by EthanGeeee** [comment]
See #3 
Updated Link using International Web Archive, to last working version available (2017).
Updated point a. to read differently, as page was irrelevant to point.

**Comment by CrimsonTome** [comment]
Issue will now be closed, thank you.
